server:
  port: 8005

spring:
  redis:
    database: 0
    host: 121.4.149.240
    port: 6379
    password: redis123

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置域名
website:
  domain-name: news.com
