############################################################
#
# article 静态化微服务
# web访问端口号  约定：8002
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  # tomcat默认大小2M，超过2M的文件不会被捕获，需要调整此处大小为100MB或者-1即可

############################################################
#
# 配置项目信息
#
############################################################
spring:
  profiles:
    active: dev   # yml中配置文件的环境配置 dev：开发环境 test：测试环境 prod：生产环境
  application:
    name: service-article-maker
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://news:news123@121.4.149.240:27017
      database: news-dev
  freemarker:
    charset: UTF-8
    content-type: text/html
    suffix: .ftl
    template-loader-path: classpath:/templates/
  rabbitmq:
    host: 121.4.149.240
    port: 5672
    username: admin
    password: admin123
    virtual-host: news-dev

############################################################
#
# eureka client 配置信息
#
############################################################
eureka:
  # 自定义eureka server的信息
  # server:
  #   hostname: eureka
  #   port: 7000
  # 所有的微服务都必须要注册到eureka中
  client:
    # 是否要把当前的eureka server注册到自己
    register-with-eureka: true
    # 从注册中心获得检索服务实例 server没有必要 直接false即可
    fetch-registry: true
    # 注册中心的服务地址 高可用集群则配置多个地址
    service-url:
      defaultZone: http://eureka-cluster-7001:7001/eureka/,http://eureka-cluster-7002:7002/eureka/,http://eureka-cluster-7003:7003/eureka/

############################################################
#
# freemarker 配置
#
############################################################
freemarker:
  html:
    article: E:\workspace\news-dev\freemarker

